# Constants
# Currently set to 1 namespace.
{{$NAMESPACES := DefaultParam .namespaces 1}}
{{$PODS_PER_NODE := DefaultParam .podsPerNode 10}}
{{$QPS := DefaultParam .qps 10}}
{{$POD_RESOURCE_REQUEST_FUZZ_FACTOR := DefaultParam .fuzzFactor .9}}
{{$POD_GROUP_LABEL := DefaultParam .groupLabel "cluster-loader"}}
# Adjust the following two for your cluster -
# kubectl get node -o json | jq -r ".items[].status.allocatable.cpu"
{{$NODE_FREE_CPU := DefaultParam .NODE_FREE_CPU 1}}
# kubectl get node -o json | jq -r ".items[].status.allocatable.memory"
# In MB
{{$NODE_FREE_MEM := DefaultParam .NODE_FREE_MEM 3840}}

# Variables
{{$NODES_PER_NAMESPACE := DivideInt .Nodes $NAMESPACES}}
{{$PODS_PER_NAMESPACE := MultiplyInt $PODS_PER_NODE $NODES_PER_NAMESPACE}}
{{$TOTAL_PODS := MultiplyInt $PODS_PER_NODE $NAMESPACES}}


# Pod Resource proportional to node to ensure consistent triggering of scale-up
{{$POD_CPU_MILLI := DivideFloat $NODE_FREE_CPU (MultiplyFloat $PODS_PER_NODE $POD_RESOURCE_REQUEST_FUZZ_FACTOR)}}
{{$POD_MEMORY_MB := DivideFloat $NODE_FREE_MEM (MultiplyFloat $PODS_PER_NODE $POD_RESOURCE_REQUEST_FUZZ_FACTOR)}}

name: SimpleBringUp
namespace:
  number: 1
tuningSets:
- name: Uniform-QPS
  qpsLoad:
    qps: {{$QPS}}

steps:
- name: Start-Measurements
  measurements:
  - Identifier: ScaleUpTimer
    Method: Timer
    Params:
      action: start
      label: scaleUpTime
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = {{$POD_GROUP_LABEL}}
      threshold: 1h
  - Identifier: SchedulingThroughput
    Method: SchedulingThroughput
    Params:
      action: start
      labelSelector: group = {{$POD_GROUP_LABEL}}

- name: Create-CL2-Pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$NAMESPACES}}
      replicasPerNamespace: 1
      tuningSet: Uniform-QPS
      objectBundle:
        - basename: deployment
          objectTemplatePath: deployment.yaml
          templateFillMap:
            Replicas: {{$PODS_PER_NAMESPACE}}
            Group: {{$POD_GROUP_LABEL}}
            CpuRequest: {{$POD_CPU_MILLI}}m
            MemoryRequest: {{$POD_MEMORY_MB}}M

- name: Wait-For-Scale-Up-Complete
- measurements:
    - Identifier: WaitingForPods
      Method: WaitForRunningPods
      Params:
        labelSelector: group = {{$POD_GROUP_LABEL}}
        desiredPodCount: {{$TOTAL_PODS}}
        timeout: 1h

- name: Stop-Timing-For-Scale-Up
- measurements:
    - Identifier: ScaleUpTimer
      Method: Timer
      Params:
        action: stop
        label: scaleUpTime

- name: Start-Timing-For-Scale-Down
- measurements:
    - Identifier: ScaleDownTimer
      Method: Timer
      Params:
        action: start
        label: scaleDownTime

- name: Delete-CL2-Pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$NAMESPACES}}
      replicasPerNamespace: 0
      tuningSet: Uniform-QPS
      objectBundle:
        - basename: deployment
          objectTemplatePath: deployment.yaml

- name: Wait-For-Scale-Down-Complete
- measurements:
    - Identifier: WaitingForPods
      Method: WaitForRunningPods
      Params:
        labelSelector: group = {{$POD_GROUP_LABEL}}
        desiredPodCount: 0
        timeout: 1h

- name: Stop-Timing-For-Scale-Down
- measurements:
    - Identifier: ScaleDownTimer
      Method: Timer
      Params:
        action: stop
        label: scaleDownTime

- name: Stop-Measurements
- measurements:
    - Identifier: PodStartupLatency
      Method: PodStartupLatency
      Params:
        action: gather
    - Identifier: SchedulingThroughput
      Method: SchedulingThroughput
      Params:
        action: gather
        labelSelector: group = {{$POD_GROUP_LABEL}}
